### ISSUE TITLE
API responds with 422 but empty response body.

### ISSUE THREAD

**Issue by tonykiselis** [mailersend/mailersend-php#36]
### Summary

Validation error response from API results in empty response content.

### Expected Results

I expect to get a validation error. For example, the email host is not verified as shown in the documentation example.

### Actual Results

API responds with status code 422 but an empty string.

### Steps to Reproduce

1. Set up a mailersend acc. Do not set up email hosts.
2. Sent valid (according to request validator) email using a host which is not set in Mailersend acc.
3. See that response contents are: ''

This issue hurts logging and makes development harder, especially if the developer does not have direct access to prod Mailersend acc.

May not be related to PHP SDK per se. But that's what I was using at the time.

**Comment by fosron** [comment]
Email domain must be setup to use the API.
