### ISSUE TITLE
can't send an api request from a simple post request

### ISSUE THREAD

**Issue by viplike** [mailersend/mailersend-php#41]
hey, can your api be used via a simple post request or not? For example, I'm using this code at the moment:

```
if(Yii::$app->request->isPost){
      $email = new MailerSendMessage();
      $email->setRecipient('mail@mail.com', 'User name');
      $email->setSubject('Password reset');
      $email->setView('password-reset-token');
      $email->send();
}
```

and it shows me an error: 

```
[url] /v1/email [http method] POST [status code] 403 [reason phrase] Forbidden
```

If I'm using the same code via console app, but not a browser post request, it's working fine

**Comment by fosron** [comment]
`403` error means your API key or user does not have enough permissions to use email API. For further questions contact us over at mailersend.com/contact-us.
