### ISSUE TITLE
MailerSendValidationException: Unprocessable Entity

### ISSUE THREAD

**Issue by phaax** [mailersend/mailersend-php#8]
Using the example code I'm getting a **MailerSendValidationException: Unprocessable Entity**

`use MailerSend\MailerSend;
use MailerSend\Helpers\Builder\Recipient;
use MailerSend\Helpers\Builder\EmailParams;

$mailersend = new MailerSend(['api_key' => '**MYAPIKEY**']);

$recipients = [
    new Recipient('**my_personal_email@home**', 'Your Client'),
];

$emailParams = (new EmailParams())
    ->setFrom('**from@our_registered_domain**')
    ->setFromName('Your Name')
    ->setRecipients($recipients)
    ->setSubject('Subject')
    ->setHtml('This is the HTML content')
    ->setText('This is the text content');

$mailersend->email->send($emailParams);`

I have no idea what I'm doing wrong here.

**Comment by fosron** [comment]
Please use https://www.mailersend.com/contact-us for support questions.
