### ISSUE TITLE
Schedule email is not working on bulksend

### ISSUE THREAD

**Issue by asimsarwar73** [mailersend/mailersend-php#89]
### Summary
'send_at' => $params->getSendAt()
This thing is not working on bulk email send.

### Expected Results
Email should be schedule on bulk send. 

### Steps to Reproduce

You can set send_at param and send bulk email you will get bug on this case.

**Comment by fosron** [comment]
Please contact our support for sending related questions.

**Comment by asimsarwar73** [comment]
okay
